version: "3"
services:
  node-app:
    image: node-app-image
    build: .
    ports:
      - "3001:4000"
    env_file:
      - ./.env

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hgomez
      - MONGO_INITDB_ROOT_PASSWORD=mypassword