version: "3"
services:
  node-app:
    image: node-app-image
    build: .
    ports:
      - "3001:4000"
    env_file:
      - ./.env

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hgomez
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
